name: blimpy
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  basic:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: blimpy
        run: echo blimpy


